<?php

namespace AiBuddy\OpenAi;

final class Response {
	public Query $query;

	/**
	 * contains items generated by the AI
	 */
	public array $results;

	/**
	 * contains the raw response from the API
	 */
	public array $raw;

	public function __construct( Query $query, array $results, array $raw ) {
		$this->query   = $query;
		$this->results = $results;
		$this->raw     = $raw;
	}
}
